name: Trigger auto deployment for maggietestrevisionapp

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/maggietestrevisionapp-AutoDeployTrigger-cc83590d-67b6-4ca0-872f-b83d482f43fc.yml'
  workflow_dispatch:

jobs:
  deploy-existing-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MAGGIETESTREVISIONAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MAGGIETESTREVISIONAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MAGGIETESTREVISIONAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy existing image to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: maggiehou-containerapp
          containerAppName: maggietestrevisionapp

          # ★ 這裡改成你要部署的映像（建議用唯一 tag，如 commit SHA）
          imageToDeploy: maggieacr.azurecr.io/maggieacr.azurecr.io/dotnet/samples:aspnetapp

          # 若你的 Container App 尚未綁定 ACR 拉取權限，先用帳密讓動作幫你設好（第一次常用）
          registryUrl: maggieacr.azurecr.io
          registryUsername: ${{ secrets.MAGGIETESTREVISIONAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MAGGIETESTREVISIONAPP_REGISTRY_PASSWORD }}

          # （可選）若要同時套用 ingress/port/env/scale 等設定，可加：
          # yamlConfigPath: ./containerapp.yaml

